//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/", ConfigurationName="NumberConversionSoapType")]
public interface NumberConversionSoapType
{
    
    // CODEGEN: Generating message contract since element name NumberToWordsResult from namespace http://www.dataaccess.com/webservicesserver/ is not marked nillable
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    NumberToWordsResponse NumberToWords(NumberToWordsRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    System.Threading.Tasks.Task<NumberToWordsResponse> NumberToWordsAsync(NumberToWordsRequest request);
    
    // CODEGEN: Generating message contract since element name NumberToDollarsResult from namespace http://www.dataaccess.com/webservicesserver/ is not marked nillable
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    NumberToDollarsResponse NumberToDollars(NumberToDollarsRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    System.Threading.Tasks.Task<NumberToDollarsResponse> NumberToDollarsAsync(NumberToDollarsRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class NumberToWordsRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="NumberToWords", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
    public NumberToWordsRequestBody Body;
    
    public NumberToWordsRequest()
    {
    }
    
    public NumberToWordsRequest(NumberToWordsRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
public partial class NumberToWordsRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
    public ulong ubiNum;
    
    public NumberToWordsRequestBody()
    {
    }
    
    public NumberToWordsRequestBody(ulong ubiNum)
    {
        this.ubiNum = ubiNum;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class NumberToWordsResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="NumberToWordsResponse", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
    public NumberToWordsResponseBody Body;
    
    public NumberToWordsResponse()
    {
    }
    
    public NumberToWordsResponse(NumberToWordsResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
public partial class NumberToWordsResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string NumberToWordsResult;
    
    public NumberToWordsResponseBody()
    {
    }
    
    public NumberToWordsResponseBody(string NumberToWordsResult)
    {
        this.NumberToWordsResult = NumberToWordsResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class NumberToDollarsRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="NumberToDollars", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
    public NumberToDollarsRequestBody Body;
    
    public NumberToDollarsRequest()
    {
    }
    
    public NumberToDollarsRequest(NumberToDollarsRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
public partial class NumberToDollarsRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
    public decimal dNum;
    
    public NumberToDollarsRequestBody()
    {
    }
    
    public NumberToDollarsRequestBody(decimal dNum)
    {
        this.dNum = dNum;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class NumberToDollarsResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="NumberToDollarsResponse", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
    public NumberToDollarsResponseBody Body;
    
    public NumberToDollarsResponse()
    {
    }
    
    public NumberToDollarsResponse(NumberToDollarsResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
public partial class NumberToDollarsResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string NumberToDollarsResult;
    
    public NumberToDollarsResponseBody()
    {
    }
    
    public NumberToDollarsResponseBody(string NumberToDollarsResult)
    {
        this.NumberToDollarsResult = NumberToDollarsResult;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface NumberConversionSoapTypeChannel : NumberConversionSoapType, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class NumberConversionSoapTypeClient : System.ServiceModel.ClientBase<NumberConversionSoapType>, NumberConversionSoapType
{
    
    public NumberConversionSoapTypeClient()
    {
    }
    
   
    public NumberConversionSoapTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    NumberToWordsResponse NumberConversionSoapType.NumberToWords(NumberToWordsRequest request)
    {
        return base.Channel.NumberToWords(request);
    }
    
    public string NumberToWords(ulong ubiNum)
    {
        NumberToWordsRequest inValue = new NumberToWordsRequest();
        inValue.Body = new NumberToWordsRequestBody();
        inValue.Body.ubiNum = ubiNum;
        NumberToWordsResponse retVal = ((NumberConversionSoapType)(this)).NumberToWords(inValue);
        return retVal.Body.NumberToWordsResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<NumberToWordsResponse> NumberConversionSoapType.NumberToWordsAsync(NumberToWordsRequest request)
    {
        return base.Channel.NumberToWordsAsync(request);
    }
    
    public System.Threading.Tasks.Task<NumberToWordsResponse> NumberToWordsAsync(ulong ubiNum)
    {
        NumberToWordsRequest inValue = new NumberToWordsRequest();
        inValue.Body = new NumberToWordsRequestBody();
        inValue.Body.ubiNum = ubiNum;
        return ((NumberConversionSoapType)(this)).NumberToWordsAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    NumberToDollarsResponse NumberConversionSoapType.NumberToDollars(NumberToDollarsRequest request)
    {
        return base.Channel.NumberToDollars(request);
    }
    
    public string NumberToDollars(decimal dNum)
    {
        NumberToDollarsRequest inValue = new NumberToDollarsRequest();
        inValue.Body = new NumberToDollarsRequestBody();
        inValue.Body.dNum = dNum;
        NumberToDollarsResponse retVal = ((NumberConversionSoapType)(this)).NumberToDollars(inValue);
        return retVal.Body.NumberToDollarsResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<NumberToDollarsResponse> NumberConversionSoapType.NumberToDollarsAsync(NumberToDollarsRequest request)
    {
        return base.Channel.NumberToDollarsAsync(request);
    }
    
    public System.Threading.Tasks.Task<NumberToDollarsResponse> NumberToDollarsAsync(decimal dNum)
    {
        NumberToDollarsRequest inValue = new NumberToDollarsRequest();
        inValue.Body = new NumberToDollarsRequestBody();
        inValue.Body.dNum = dNum;
        return ((NumberConversionSoapType)(this)).NumberToDollarsAsync(inValue);
    }
}
